### ISSUE TITLE
Not compatible with Python 3

### ISSUE THREAD

**Issue by davidystephenson** [johnb30/gdelt_download#1]
Several features, including print statements, exception naming, and url requests result in errors, as they are compatible with Python 3. Of course, the extent to which this is a bug is debatable.

A cursory examination of your code indicates that compatibility may be possible. I may pursue finding solutions to these challenges, if you would be amenable.

**Comment by johnb30** [comment]
My only issue with making the print statements Python 3 compatible is that the entire script still wouldn't be compatible with 3. The issue is that `boto` is only compatible with 2.x. I'm open to just making a note that the upload functions aren't compatible with 3, but the rest of the script is. I'll give this some thought. I'd also be open to a pull request.

**Comment by davidystephenson** [comment]
I'll start examining pull request possibilities. There would be a few other syntax compatibility issues, such as exception naming. However, there are module issues that disable both historical downloading and uploading with Python 3: `urllib2` and `boto`.

As stated in the `urllib2` [documentation](http://docs.python.org/library/urllib2.html):

```
The urllib2 module has been split across several modules in Python 3.0 named urllib.request and urllib.error. The 2to3 tool will automatically adapt imports when converting your sources to 3.
```

I've had a good experience working with [requests](http://docs.python-requests.org/en/latest/#), an excellent module which is 2 and 3 compatible

I'm not a `boto` user, so I don't know how easy finding a compatible option would be. Mitchell Garnaat, the boto developer, has begun working on [aws-cli](https://github.com/aws/aws-cli), which supposedly provides the same functionality, and is in turn based on the new base project [botocore](https://github.com/boto/botocore), both of wich are 2 and 3 compatible.

I'm not sure if you've eliminated these options already or exactly what would be necessary to utilize them, but I'm happy to begin exploring.

**Comment by johnb30** [comment]
Right, switching to `requests` wouldn't be hard. From a cursory glance it doesn't seem like switching to `botocore` would be difficult either. It's just a matter of changing a few lines in the scripts. 

My main issue is that I don't have that much time right now, and I would have to test every function again. I might be able to get around to this by the end of the weekend.

**Comment by davidystephenson** [comment]
Very reasonable. I'll check back in next week perhaps and see how I can be of assistance. I will also be attending the GDELT Hackathon on the 27th, which I believe you may be as well, so perhaps we can interface there.

**Comment by johnb30** [comment]
Great. Yes, I'm the one organizing the hackathon. The actual hackathon is on the 28th. It's just a couple of talks on Friday afternoon (27th).

**Comment by davidystephenson** [comment]
Yes, the 28th, my mistake. Feel free to comment here if there are specific ways I can assist that come to mind.

**Comment by johnb30** [comment]
Okay, everything should work with Python 3 now, except the upload commands. I didn't feel like `botocore` was far enough along (documentation, API) right now to use in this project. Let me know if anything is broken now.
